@@in# "fn handle(data ?&Data) {"
@@in# "if data != none {"
@@in# "data or { panic('failed to unwrap data.id') }"
@@in# "((data or { panic('failed to unwrap data.id') }).id)"
@@notin# "println(data.id)"
